In [1]:
import numpy as np

### Create an array

In [2]:
# create an array from a lst using np.array
simple_list = [6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
#create a numpy array
arr = np.array([1,2,3,])
arr

array([1, 2, 3])

In [4]:
list_of_lists = ([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [6]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((2,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# create array of numbers between 1 and 100  using linspace with 10 spaces
nums =np.linspace(start = 1, stop = 100, num=10)
print(nums)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [14]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [15]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
# rand() method creates an array of random numbers of the given shape
# and between (0, 1)
np.random.rand(2,4)

array([[0.81258202, 0.55041739, 0.83352399, 0.29162407],
       [0.67471414, 0.83547845, 0.8986303 , 0.81179323]])

In [18]:
#The randn() returns a set of values from the standard normal distribution

np.random.randn(2,4)

array([[-2.17713393, -0.41000425,  0.6037208 ,  0.05752776],
       [-1.75155547,  0.01505039,  1.96979601, -0.53266301]])

In [19]:
np.random.rand(2,5)

array([[0.38355494, 0.53017413, 0.61977285, 0.99334381, 0.30761972],
       [0.1751443 , 0.53736582, 0.34351573, 0.0948164 , 0.22338487]])

In [20]:
# Returns 15 random integers between 0 and 10
np.random.randint(0,10,15)

array([7, 6, 6, 9, 3, 0, 7, 1, 5, 9, 1, 3, 5, 3, 5])

In [21]:
# Returns 100 random integers between 20 and 73
np.random.randint(20,73,100)

array([68, 45, 27, 66, 65, 65, 28, 68, 62, 65, 60, 30, 65, 30, 70, 60, 69,
       46, 20, 42, 62, 70, 57, 43, 22, 71, 51, 64, 20, 34, 61, 37, 22, 69,
       38, 37, 69, 58, 68, 72, 31, 64, 34, 69, 41, 49, 23, 31, 44, 70, 27,
       64, 34, 70, 65, 28, 20, 72, 35, 23, 26, 51, 57, 71, 62, 42, 38, 24,
       35, 33, 66, 62, 70, 21, 37, 26, 53, 40, 44, 26, 44, 68, 33, 56, 62,
       31, 26, 36, 38, 33, 55, 31, 21, 68, 67, 32, 33, 44, 61, 32])

In [22]:
rand_array = np.random.randint(0,10,5)
rand_array

array([7, 1, 5, 6, 1])

In [23]:
# create an arrayof even numbers between 2(inclusive) to 20(exclusive)
sample_array=np.arange(start=2,stop=20,step=2)
sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
sample_array.min()

2

In [25]:
sample_array.argmin()

0

In [26]:
rand_array.argmin()

1

In [27]:
rand_array.max()

7

In [28]:
sample_array.argmax()

8

In [29]:
rand_array.argmax()

0

In [30]:
sample_array.dtype

dtype('int32')

In [31]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a=np.random.rand(2,3)
a

array([[0.02927937, 0.26042922, 0.71736323],
       [0.81660154, 0.21613043, 0.77160109]])

In [34]:
a.T

array([[0.02927937, 0.81660154],
       [0.26042922, 0.21613043],
       [0.71736323, 0.77160109]])

In [35]:
sample_array = np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [38]:
sample_array = sample_array.reshape(3,6)
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [39]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [40]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [41]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [42]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

# Two Dimensional array

In [43]:
import numpy as np

In [44]:
# create a 3x3 matrix
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [45]:
sample_matrix[2:2]#just returning the matrix  

array([], shape=(0, 4), dtype=int32)

In [46]:
# slicing 2D array
#[row][colmn]
sample_matrix[1][2]

54

In [47]:
sample_matrix[1:,:2]

array([[15,  2],
       [56, 76]])

In [48]:
sample_matrix[2][2]

24

In [49]:
# returns the second row
sample_matrix[2]

array([56, 76, 24,  7])

In [50]:
import numpy as np

In [51]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [53]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [54]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [55]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [56]:
np.max(sample_array)

30

In [57]:
np.min(sample_array)

1

In [58]:
np.argmax(sample_array)

29

In [59]:
np.argmin(sample_array)

0

In [60]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [61]:
np.std(sample_array)

8.65544144839919

In [62]:
np.var(sample_array)

74.91666666666667

In [63]:
np.mean(sample_array)

15.5

In [64]:
array=np.random.randn(3,4)  ### Normal distribution
array

array([[ 0.95505492, -1.29398926,  0.96666651, -1.80683257],
       [ 1.49177505, -0.26742761,  0.33333445, -0.1504181 ],
       [-0.04279202, -0.69018327,  0.16949951,  1.1474676 ]])

In [65]:
np.round(array,decimals=3)

array([[ 0.955, -1.294,  0.967, -1.807],
       [ 1.492, -0.267,  0.333, -0.15 ],
       [-0.043, -0.69 ,  0.169,  1.147]])

In [66]:
sports=np.array(['Golf','Cricket','Football','Cricket'])
np.unique(sports)

array(['Cricket', 'Football', 'Golf'], dtype='<U8')

### Assessment ###
#### 1) Create a null vector of size 10
#### 2)Create a null vector of size 10 but the 5th value should be 1
#### 3)Create a vector with vaues ranging from 10 to 65
#### 4) Reverse the above vector
#### m5)Create a 3x3 matrix with values ranging from 0 to 8 

In [67]:
#1
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
#2
vector[4]=1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [70]:
#3
v = np.arange(10,65)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64])

In [73]:
#4
v.flip()
v

AttributeError: 'numpy.ndarray' object has no attribute 'flip'

In [76]:
#5
x =  np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])