# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [2]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [7]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((3,3),dtype = int)

array([[       0,        1,        0],
       [67241985,      748,        0],
       [     768,        0,        0]])

In [7]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [8]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2,4)

array([[0.58757525, 0.32413975, 0.55214511, 0.26414679],
       [0.5037265 , 0.66474238, 0.21352798, 0.42317162]])

In [13]:
np.random.rand(2,7)

array([[0.06727425, 0.55026486, 0.22319472, 0.18231932, 0.63427568,
        0.9114728 , 0.29175339],
       [0.83648557, 0.93942284, 0.02879975, 0.01782946, 0.28193499,
        0.46611498, 0.73617812]])

In [14]:
np.random.randint(2,10)

4

In [15]:
np.random.randint(20,56,100)

array([20, 30, 52, 37, 23, 46, 20, 23, 35, 49, 31, 49, 47, 40, 31, 43, 35,
       26, 47, 46, 51, 35, 46, 47, 28, 34, 26, 32, 32, 55, 52, 30, 40, 51,
       38, 30, 29, 23, 24, 22, 38, 33, 47, 28, 41, 40, 46, 32, 26, 52, 47,
       31, 33, 39, 22, 55, 50, 36, 37, 52, 42, 41, 21, 40, 41, 54, 21, 37,
       50, 21, 22, 38, 48, 43, 43, 44, 20, 50, 26, 54, 55, 40, 21, 50, 53,
       53, 37, 45, 21, 37, 24, 35, 24, 21, 51, 34, 45, 49, 37, 33])

In [16]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
rand_array=np.random.randint(0,100,20)
rand_array

array([71, 13, 61, 89, 49, 31, 73, 87, 29, 82, 21, 10, 35, 57, 66, 96, 39,
       89, 50, 60])

In [18]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
rand_array.max()

96

In [20]:
rand_array.argmax()

15

In [21]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sample_array.shape

(30,)

In [23]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
sample_array.dtype

dtype('int32')

In [25]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.random.rand(2,3)
a

array([[0.48435964, 0.27492501, 0.62282426],
       [0.4463855 , 0.4735606 , 0.46259537]])

In [28]:
a.T

array([[0.48435964, 0.4463855 ],
       [0.27492501, 0.4735606 ],
       [0.62282426, 0.46259537]])

In [29]:
import numpy as np

In [30]:
sample_array=np.arange(10,21)


In [31]:
sample_array[8]

18

In [32]:
sample_array[2:5]

array([12, 13, 14])

In [33]:
sample_array[[2,5]]

array([12, 15])

In [34]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [36]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [38]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [39]:
sample_matrix[0][2]

1

In [40]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [42]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [43]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

###  Selection techniques

In [44]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [46]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [48]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [49]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [50]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [51]:
np.max(sample_array)

30

In [52]:
np.min(sample_array)

1

In [53]:
np.argmax(sample_array)

29

In [54]:
np.argmin(sample_array)

0

In [55]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [56]:
np.std(sample_array)

8.65544144839919

In [57]:
np.var(sample_array)


74.91666666666667

In [58]:
np.mean(sample_array)

15.5

In [59]:
array=np.random.randn(3,6)
array

array([[-1.55491027,  0.78108062,  0.20585003,  1.64516384, -0.78903125,
        -0.86074011],
       [-0.74553864, -0.22977997, -1.22972391, -2.28690948,  0.2152232 ,
        -0.40749897],
       [-0.57858808,  0.25734996, -0.34925228,  0.84929211,  1.03885774,
         0.24807656]])

In [60]:
np.round(array,decimals=2)

array([[-1.55,  0.78,  0.21,  1.65, -0.79, -0.86],
       [-0.75, -0.23, -1.23, -2.29,  0.22, -0.41],
       [-0.58,  0.26, -0.35,  0.85,  1.04,  0.25]])

In [61]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')